# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "camp-app"
client_id = "672cffc44067d947f995095beaf0f5e5"
application_url = "https://keeps-antibody-rid-however.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_product_listings,write_products, write_discounts"

[auth]
redirect_urls = [
  "https://keeps-antibody-rid-however.trycloudflare.com/auth/callback",
  "https://keeps-antibody-rid-however.trycloudflare.com/auth/shopify/callback",
  "https://keeps-antibody-rid-however.trycloudflare.com/api/auth/callback",
  "https://keeps-antibody-rid-however.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dtm-camp-store2.myshopify.com"
